[workspace]
resolver = "3"
exclude = ["src/userspace/nvme", "src/userspace/test_driver", "xtask"]
members = ["src/kernel"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 2
[profile.release.package.kernel]
codegen-units = 1
