name: Validation

on:
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  validation:
    name: Pre-commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.rustup/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install --profile minimal --component rust-src,rustfmt,clippy nightly-2025-07-12
          rustup target add x86_64-unknown-none
          cargo install cargo-sort

      - name: Configure Environment
        run: rustup default nightly

      - name: Check Formatting
        run: cargo fmt --check

      - name: Check Dependency Ordering
        run: cargo sort --workspace --grouped --check

      - name: Check Build Status
        run: cargo clippy --target x86_64-unknown-none
